apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    author: jeral
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pod
  template:
    metadata:
      name: postgres-container
      namespace: production
      labels:
        app: postgres-pod
    spec:
      containers:
      - name: postgres-database
        image: postgres:13
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
        env:
          - name: POSTGRES_USER
            value: jeral
          - name: POSTGRES_PASSWORD
            value: '1234'
          - name: POSTGRES_DB
            value: bconic_db
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
          