apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: production
spec:
  selector:
    app: pgadmin-pod
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP