name: Deploy Frontend to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_sha:
        description: 'Docker Image SHA'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - minikube
        default: minikube

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout SCM
      - name: Checkout k8s manifests
        uses: actions/checkout@v4

      # Update Image Tag
      - name: Update image tag in deployment
        run: |
          echo "Updating frontend image to: jeralsandeeptha/bconic-frontend:${{ github.event.inputs.image_sha }}"
          echo "Target file: minikube/bconic-frontend/deployment.yaml"
          
          # Install yq if not present
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod a+x /usr/local/bin/yq
          fi
          
          # Update the deployment file
          yq eval '.spec.template.spec.containers[0].image = "jeralsandeeptha/bconic-frontend:'${{ github.event.inputs.image_sha }}'"' -i minikube/bconic-frontend/deployment.yaml
          
          echo "Updated deployment file:"
          cat minikube/bconic-frontend/deployment.yaml

      # Commit and Push changes
      - name: Commit updated deployment file
        run: |
          git config --local user.email "jeral.sandeeptha1@gmail.com"
          git config --local user.name "JeralSandeeptha"

          # Configure git to use PAT for authentication
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/JeralSandeeptha/BConic-Kubernates-Deployment.git

          git add minikube/bconic-frontend/deployment.yaml
          git diff --staged --quiet || git commit -m "Deploy: Update frontend image to ${{ github.event.inputs.image_sha }}"
          git push origin main