name: Deploy Frontend to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_sha:
        description: 'Docker Image SHA'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - minikube
        default: minikube

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout SCM
      - name: Checkout k8s manifests
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Debug PAT token availability
        run: |
          echo "Checking PAT token availability..."
          if [ -n "${{ secrets.PAT_TOKEN }}" ]; then
            echo "✅ PAT_TOKEN secret is available"
            echo "Token length: ${#{{ secrets.PAT_TOKEN }}} characters"
          else
            echo "❌ PAT_TOKEN secret is empty or not available"
          fi

      # Update Image Tag
      - name: Update image tag in deployment
        run: |
          echo "Updating frontend image to: jeralsandeeptha/bconic-frontend:${{ github.event.inputs.image_sha }}"
          
          # Install yq
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
          
          # Update the deployment file
          yq eval '.spec.template.spec.containers[0].image = "jeralsandeeptha/bconic-frontend:'${{ github.event.inputs.image_sha }}'"' -i minikube/bconic-frontend/deployment.yaml
          
          echo "✅ Updated deployment file"

      # Commit and Push changes
      - name: Commit updated deployment file
        run: |
          git config --local user.email "jeral.sandeeptha1@gmail.com"
          git config --local user.name "JeralSandeeptha"

          # Configure git to use PAT for authentication
          git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/JeralSandeeptha/BConic-Kubernates-Deployment.git

          git add minikube/bconic-frontend/deployment.yaml
          git commit -m "Deploy: Update frontend image to ${{ github.event.inputs.image_sha }}" || exit 0
          git push